### ISSUE TITLE
Footer adjustment

### ISSUE THREAD

**Issue by MohdSaquib114** [J0SAL/Decentralized-Expense-Tracker#38] opened 2023-05-22 17:07 UTC
### Is your feature request related to a problem? Please describe.

Footer is not properly adjusted to the bottom of the body, there is a gap between the body bottom and the footer element

### Describe the solution you'd like

i dont no if it will work or not but i think adjusting its margin will solve this

**Comment by Aditi323** [comment] 2023-05-22 17:53
Could you please assign me this as a GSSOC Contributor.

**Comment by Himanshi1207** [comment] 2023-05-22 19:34
Please assign it to me

**Comment by MohdSaquib114** [comment] 2023-05-23 11:47
try it if you think you can make footer look good

**Comment by HimanshiDafouty** [comment] 2023-05-24 03:39
I  request you to kindly assign this to me ,  as I am confident in my abilities to deliver relevant results. Thank you for considering me.

**Comment by Himanshi1207** [comment] 2023-05-24 05:11
Working on it

**Comment by hansu03** [comment] 2023-05-24 06:31
I would like request I would love  to work  and contribute on footer section . 
If you haven't assigned to anyone then please assign to me

**Comment by MohdSaquib114** [comment] 2023-05-25 08:36
> Hey @MohdSaquib114, can you provide some visuals (screenshots) that support your claim?

![Screenshot 2023-05-25 140526](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/107548091/3e43c682-185e-4b18-a465-18fba21334f0)
![Screenshot 2023-05-25 140601](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/107548091/290e0bdb-7324-4a1d-8b86-4b10dbff588c)

**Comment by J0SAL** [comment] 2023-05-25 18:46
This functionality was intended

**Closed** 2023-05-28 19:34 UTC
Labels: enhancement
